baseURL: /
theme: cupper-hugo-theme
disqusShortname:
enableGitInfo: false

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  homeMetaContent:
    # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: 
  katex: false
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: true
  moveFooterToHeader: false
  #navTitleText: Cupper Theme
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js  
enableRobotsTXT: true
DefaultContentLanguage: en
DefaultContentLanguageInSubdir: true
languages:
  lv:
    languageName: Latviski ğŸ‡±ğŸ‡»
    contentdir: content
    title: â˜® DV
    description:
    weight: 0
    logoAlt: Lapas logo, lupa ar eÅ†Ä£eÄ¼a spÄrniem un kafijas krÅ«zÄ«te
    menu:
     nav:
       - name: SÄkums
         url: /lv/
         weight: 1
       - name: Ieraksti
         url: /lv/post/
         weight: 2
       - name: TÄ“mturi
         url: /lv/tags/
         weight: 3
       - name: Foto
         url: /lv/gallery/
         weight: 4  
       - name: Par
         url: /lv/about/
         weight: 5
    params:
      footer: 2023 Â© DÄvis VilcÄns
  en:
    languageName: English ğŸ‡¬ğŸ‡§
    contentdir: content
    title: â˜® DV
    weight: 1
    logoAlt: Site logo, lupa with angel wings and a cup of coffee
    menu:
     nav:
       - name: Home
         url: /en/
         weight: 1
       - name: Entries
         url: /en/post/
         weight: 2
       - name: Tags
         url: /en/tags/
         weight: 3
       - name: Photos
         url: /en/gallery/
         weight: 4 
       - name: About
         url: /en/about/
         weight: 5
    params:
      footer: 2023 Â© DÄvis VilcÄns   
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
