baseURL: /
theme: cupper-hugo-theme
disqusShortname:
enableGitInfo: false

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  hideHomeSection: true
  homeMetaContent: Dﾄ」is' WWW playground. Notes, thoughts, ideas. 
    # For more date formats see https://gohugo.io/functions/format/
# dateFormat: Jan 2, 2006
  dateFormats:
    en: Jan 2, 2006
    lv: Jan 2, 2006
  codePenUser: 
  katex: false
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: false
# navTitleText: Cupper Theme
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js
  logoAlt: Site logo, lupa with angel wings and a cup of coffee
# description: Davis' WWW playground. Notes, thoughts, ideas.
enableRobotsTXT: true
DefaultContentLanguage: en
DefaultContentLanguageInSubdir: false
languages:
  lv:
    languageName: Latviski ｱｻ
    staticDir: static
    title: 笘ｮ DV
#   dateFormat: Jan 2, 2006
    weight: 0
    menu:
     nav:
#       - name: Sﾄ〔ums
#         url: /lv/
#         weight: 1
       - name: Ieraksti
         url: /lv/
         weight: 1
       - name: Tﾄ杜turi
         url: /lv/tags/
         weight: 2
#       - name: Galerija
#         url: "https://gallery.dvilcans.com/lv"
         weight: 3
       - name: ﾅobrﾄｫd
         url: /lv/now/
         weight: 4
    params:
      footer: 2023 ﾂｩ Dﾄ」is Vilcﾄ］s
  en:
    languageName: English ｬｧ
    contentdir: content
    title: 笘ｮ DV
#   dateFormat: Jan 2, 2006
    weight: 1
    menu:
     nav:
#       - name: Home
#         url: /en/
#         weight: 1
       - name: Entries
         url: /en/
         weight: 1
       - name: Tags
         url: /tags/
         weight: 2
#       - name: Gallery
#         url: "https://gallery.dvilcans.com/"
         weight: 3
       - name: Now
         url: /now/
         weight: 4
    params:
      footer: 2023 ﾂｩ Dﾄ」is Vilcﾄ］s   
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
