baseURL: /
theme: cupper-hugo-theme
disqusShortname:
enableGitInfo: false
taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  hideHomeSection: true
  homeMetaContent: Dﾄ」is' WWW playground. 
    # For more date formats see https://gohugo.io/functions/format/
# dateFormat: Jan 2, 2006
  dateFormats:
    en: Jan 2, 2006
    lv: Jan 2, 2006
  codePenUser: 
  katex: false
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: false
#  navTitleText: Cupper Theme!
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  logoAlt: Site logo
# description: Davis' WWW playground. Notes, thoughts, ideas.
enableRobotsTXT: true
DefaultContentLanguage: en
DefaultContentLanguageInSubdir: false
languages:
  lv:
    languageName: Latviski ｱｻ
    staticDir: static
    title: Dﾄ」is Vilcﾄ］s
#   dateFormat: Jan 2, 2006
    weight: 0
    menu:
     nav:
#       - name: Sﾄ〔ums
#         url: /lv/
#         weight: 1
       - name: Ieraksti
         url: /lv/
         weight: 1
       - name: Tﾄ杜turi
         url: /lv/tags/
         weight: 2
#       - name: Galerija
#         url: "https://gallery.dvilcans.com/lv"
#         weight: 3
       - name: Par
         url: /lv/about/
#       - name: AI IMG
#         url: /lv/aimgen/
         weight: 5
       - name: Pakalpojumi
         url: /lv/services/
         weight: 4
#       - name: txt2img
#         url: "https://txt2img.dvilcans.com/"
#         weight: 6             
#       - name: Harry the O.G.
#         url: "https://chat.dvilcans.com/"
#         weight: 7    
#       - name: RSS
#         url: /index.xml
#         weight: 5
#     
    params:
      footer: Izveidots ar [Hugo](https://gohugo.io). Motﾄｫvs no [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Izvietots uz [Cloudflare](https://cloudflare.com).<br> ﾂｩ 2023-2024 Dﾄ」is Vilcﾄ］s
      customJs:
        - js/quizdown.js
        - js/custom_01.js
        - js/custom_02.js
        - js/quizdownHighlight.js
        - js/quizdownKatex.js
  en:
    languageName: English ｬｧ
    contentdir: content
    title: Dﾄ」is Vilcﾄ］s
#   dateFormat: Jan 2, 2006
    weight: 1
    menu:
     nav:
#       - name: Home
#         url: /en/
#         weight: 1
       - name: Entries
         url: /en/
         weight: 1
       - name: Tags
         url: /tags/
         weight: 2
#       - name: Gallery
#         url: "https://gallery.dvilcans.com/"
#         weight: 3
       - name: About
         url: /about/
#       - name: AI IMG
#         url: /aimgen/
         weight: 5
       - name: Services
         url: /services/
         weight: 4
#       - name: txt2img
#         url: "https://txt2img.dvilcans.com/"
#         weight: 6         
#       - name: Harry the O.G.
#         url: "https://chat.dvilcans.com/"
#         weight: 7
#       - name: RSS
#         url: /index.xml
#         weight: 5
    params:
      footer: Made with [Hugo](https://gohugo.io). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Cloudflare](https://cloudflare.com).<br> ﾂｩ 2023-2024 Dﾄ」is Vilcﾄ］s
      customJs:
        - js/quizdown_en.js   
        - js/custom_01.js
        - js/custom_02.js
        - js/quizdownHighlight.js
        - js/quizdownKatex.js
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2

